### ISSUE TITLE
Redstone by Creeperface01?

### ISSUE THREAD

**Issue by NycuRO** [JupiterDevelopmentTeam/JupiterDevelopmentTeam#6]

**Comment by itsu020402** [comment]
Sorry, what do you want to say...?

**Comment by NycuRO** [comment]
Can you add Redstone (Nukkit PR) by Creeperface01?

**Comment by Creeperface01** [comment]
Why? this repository is absolutely same as official, they just add simple things like blocks, items, entities (without their functions) - that's useless and if they want to help us, they should push these changes to official repository..

**Comment by Creeperface01** [comment]
I understand when @PeratX created genisys, or when other forks of Pocketmine was created (imagicalmine) - simply because the main repository was absolutely dead. But nukkit isn't. Nukkit only has less active developers. Or Steadfast - it was originally the faster version of pocketmine (for lifeboat), and then it became a separate server software, like genisys, because pocketmine was dead.

**Comment by itsu020402** [comment]
Should we not proceed with this project as it is?

**Comment by Creeperface01** [comment]
Why did you created this instead of cobtributing on official repository?

**Comment by itsu020402** [comment]
It is because Nukkit's project was cloned as it was, it did not work correctly and it had to be reconfigured.

**Comment by itsu020402** [comment]
I used Google translate because I can't speak English...
sorry

**Comment by itsu020402** [comment]
We have a dream to make a server software of Java.
We want to do it as us.
Please let us do it.

**Comment by PeratX** [comment]
Then do it from the very beginning. Good LUCK.

**Comment by itsu020402** [comment]
Thank you.

**Comment by popkechupki** [comment]
We hope continue to develop Jupiter. But we Do it after creating a goal. If you still can not accept it,  please say it.
(I'm not good at talk in English, sorry)
